spring.datasource.url=jdbc:postgresql://localhost:5432/pesquisa_eleitoral_db
spring.datasource.username=postgres
spring.datasource.password=SenhadoBancoAqui
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true